name: My GitHub Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script and include email in step
      run: echo "This is a step that contains my email 21f1006473@ds.study.iitm.ac.in"
      name: Action Step with Email (21f1006473@ds.study.iitm.ac.in)
